export const LOAD_ELEMENT_SUCCESS = "LOAD_ELEMENT_SUCCESS";
export const LOAD_COLORS_SUCCESS = "LOAD_COLORS_SUCCESS";
export const LOAD_MANUFACTURERS_SUCCESS = "LOAD_MANUFACTURERS_SUCCESS";

export const LOAD_CAR_SUCCESS = "LOAD_CAR_SUCCESS";

export const ADD_CAR_WISHLIST_SUCCESS = "ADD_CAR_WISHLIST_SUCCESS";
export const REMOVE_CAR_WISHLIST_SUCCESS = "REMOVE_CAR_WISHLIST_SUCCESS";
